language: node_js
deploy:
  provider: npm
  api_key:
    secure: cCzZ3oeyJGTLWK1Wjv3wbX/RaR55oHfOorZLK1twmB5IpC1fDcP/r2GT1cHt2gaodTBK6tpb9P+ndQ0Td7H3FCM2ESkrEoGE4q4lbUJCkAVHqbTE9WshGJSe/GJOZanzBuJrkpIhvyp2s2MQSSAVeRbbqFT3rEeDWiZ3BA0+TZa5JdXsq7AyUwrIUQRQCMn8tVujohJcN7hOEGJQcD3HW4c0fh+p6YnHOJi679gBvXSlVTh8+cTsjPFrKbaFUqma4Nt5mNNdwiTs0XpuWQe+Sg6JMJDt4nM9CmE2miw8+3xYTpuqXSGis5fD/AZDJzHup58dmnHZzn9oASanEj4akGIV93kJsvs+f8PeJwuFN1kWGuvAO1K5jrKVMWAloVSjBAzhcAnBs/Jv+LQosyuPMg7HgpXusBmiGi8jQkuGz8+Y2+BVT2RXqYkRXH2HNmr9bZTpGSaNg5arhVuE27KZmuwkJVVF6Lx0qofNhnYNXkVDnPgNivyV2xSMqkyStHC1IWnmjmpOTWzInjQPTkXNEjNY5AsTMa1i40pM0GLjNNUEJWoUXna75Vyc9RfpynD3gtnmBFEQa5YSPl2Edv+Y/s9CPpZmkB1mPKTsm5pekRSGdUiayiocDXw1+pHl+jeaiVCqyYGFDaJ2Y7xqzPvMxOnKIuwiVi9bLDH4kE472ew=

